on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npx cypress run
        # env:
        #   CYPRESS_password: ${{ secrets.TEST_PASSWORD }}
        #   CYPRESS_incorrectPassword: ${{ secrets.INCORRECT_TEST_PASSWORD }}
        #   CYPRESS_existingUsername: ${{ secrets.USERNAME }}
